// Generated by packages/web/scripts/sync-engineer-kit-stable-commands.mjs
// Source: https://www.vividkit.dev/vi/guides/commands
// Manual sync only. Do not edit by hand.

export interface EngineerKitStableCommand {
  id: string;
  title: string;
  description: string;
  argsHint?: string;
}

export const engineerKitStableCommands = [
  {
    id: 'ck:agent-browser',
    title: 'CLI tự động hóa trình duyệt tối ưu cho AI',
    description: 'Snapshot hiệu quả về context cho các tương tác web phức tạp.',
  },
  {
    id: 'ck:ai-artist',
    title: 'Tạo ảnh qua Nano Banana',
    description: '129 prompt được tuyển chọn. Bắt buộc validation.',
    argsHint: '--mode search --mode creative --mode wild --mode all --skip',
  },
  {
    id: 'ck:ai-multimodal',
    title: 'Phân tích ảnh/audio/video với Gemini API',
    description: 'Tạo ảnh (Imagen 4, Nano Banana 2), video (Veo 3, Hailuo).',
  },
  {
    id: 'ck:ask',
    title: 'Trả lời câu hỏi kỹ thuật và kiến trúc',
    description: 'Tư vấn chuyên gia cho quyết định công nghệ.',
    argsHint: '[question]',
  },
  {
    id: 'ck:backend-development',
    title: 'API Node.js, Python, Go',
    description: 'NestJS, FastAPI, Django. REST/GraphQL/gRPC.',
  },
  {
    id: 'ck:better-auth',
    title: 'Auth TypeScript: OAuth, 2FA, passkeys',
    description: 'Hỗ trợ RBAC, WebAuthn, MFA.',
  },
  {
    id: 'ck:bootstrap',
    title: 'Khởi tạo dự án đầy đủ từ đầu',
    description: 'Cài đặt tech stack, lập kế hoạch, thiết kế, và triển khai.',
    argsHint: '--full --auto --fast --parallel',
  },
  {
    id: 'ck:brainstorm',
    title: 'Brainstorm giải pháp với phân tích đánh đổi',
    description: 'Bao gồm đánh giá thẳng thắn. Điểm khởi đầu tốt cho bất kỳ tính năng nào.',
  },
  {
    id: 'ck:chrome-devtools',
    title: 'Tự động hóa với Puppeteer',
    description: 'Chụp màn hình, hiệu suất, giám sát mạng, scraping.',
  },
  {
    id: 'ck:ck-help',
    title: 'Hướng dẫn sử dụng ClaudeKit',
    description: 'Khám phá commands, skills, và workflows một cách tương tác.',
  },
  {
    id: 'ck:code-review',
    title: 'Đánh giá chất lượng code',
    description: 'Phát hiện edge case dựa trên Scout và điều phối pipeline Task.',
    argsHint: '[context] codebase codebase parallel',
  },
  {
    id: 'ck:coding-level',
    title: 'Đặt mức độ kinh nghiệm lập trình (0-5)',
    description: 'Tùy chỉnh giải thích từ người mới bắt đầu đến chuyên gia.',
  },
  {
    id: 'ck:context-engineering',
    title: 'Giám sát sử dụng context và tối ưu token',
    description: 'Kiểm tra giới hạn và tối ưu hóa mức tiêu thụ context window.',
  },
  {
    id: 'ck:cook',
    title: 'Triển khai tính năng tất cả trong một',
    description: 'Research → plan → implement → test → review. Sử dụng Claude Tasks để điều phối.',
    argsHint: '--interactive --fast --parallel --auto --no-test',
  },
  {
    id: 'ck:copywriting',
    title: 'Tiêu đề, CTA, landing page',
    description: 'Email copy, phong cách viết, copy tập trung vào chuyển đổi.',
    argsHint: '[copy-type] [context]',
  },
  {
    id: 'ck:databases',
    title: 'MongoDB, PostgreSQL, SQL/NoSQL',
    description: 'Queries, aggregation, index, migration.',
  },
  {
    id: 'ck:debug',
    title: 'Phân tích nguyên nhân gốc có hệ thống',
    description: 'Truy vết call stack, validation đa lớp. Dùng khi không biết vấn đề ở đâu.',
  },
  {
    id: 'ck:devops',
    title: 'Cloudflare, Docker, GCP, Kubernetes',
    description: 'Triển khai Workers, R2, D1, Cloud Run.',
  },
  {
    id: 'ck:docs',
    title: 'Phân tích codebase và quản lý tài liệu',
    description: 'Khởi tạo, cập nhật, hoặc tóm tắt tài liệu dự án.',
    argsHint: 'init update summarize',
  },
  {
    id: 'ck:docs-seeker',
    title: 'Tìm kiếm tài liệu thư viện/framework',
    description: 'Qua llms.txt (context7.com). Cách nhanh nhất để lấy tài liệu cập nhật.',
  },
  {
    id: 'ck:find-skills',
    title: 'Khám phá và cài đặt skill từ hệ sinh thái',
    description: 'Tìm kiếm theo khả năng hoặc mô tả task.',
  },
  {
    id: 'ck:fix',
    title: 'Sửa lỗi thông minh với định tuyến',
    description:
      'Định tuyến đến các lệnh fix chuyên biệt. Chế độ song song cho vấn đề nhiều file phức tạp.',
    argsHint: '--auto --review --quick --parallel',
  },
  {
    id: 'ck:frontend-design',
    title: 'Tạo giao diện frontend hoàn thiện',
    description: 'Từ bản thiết kế, screenshots, hoặc videos.',
  },
  {
    id: 'ck:frontend-development',
    title: 'Xây dựng frontend React/TypeScript',
    description: 'Các pattern hiện đại, MUI v7, TanStack.',
  },
  {
    id: 'ck:git',
    title: 'Thao tác Git với conventional commits',
    description: 'Tự động chia theo loại/phạm vi. Quét bảo mật trước khi commit.',
    argsHint: 'cm cp pr merge',
  },
  {
    id: 'ck:gkg',
    title: 'Phân tích code ngữ nghĩa',
    description: 'Tích hợp GitLab Knowledge Graph.',
  },
  {
    id: 'ck:google-adk-python',
    title: 'Xây dựng AI agent với Google ADK Python',
    description: 'Giao thức A2A, tích hợp MCP tools.',
  },
  {
    id: 'ck:journal',
    title: 'Viết nhật ký phân tích thay đổi',
    description: 'Ghi lại các suy nghĩ và quyết định kỹ thuật.',
  },
  {
    id: 'ck:kanban',
    title: 'Bảng điều phối AI agent',
    description: 'Trực quan hóa task cho quy trình agent.',
  },
  {
    id: 'ck:markdown-novel-viewer',
    title: 'Đọc kiểu sách qua HTTP server',
    description: 'Đọc thoải mái cho các file markdown.',
  },
  {
    id: 'ck:mcp-builder',
    title: 'Xây dựng MCP server',
    description: 'FastMCP (Python), MCP SDK (Node/TypeScript).',
  },
  {
    id: 'ck:mcp-management',
    title: 'Khám phá và quản lý MCP tools',
    description: 'Prompts, resources, và các thao tác server.',
  },
  {
    id: 'ck:media-processing',
    title: 'FFmpeg, ImageMagick, xóa nền bằng AI',
    description: 'Xử lý video/audio, ảnh, và các thao tác RMBG.',
  },
  {
    id: 'ck:mermaidjs-v11',
    title: 'Sơ đồ luồng, biểu đồ, Gantt, timeline',
    description: 'Biểu đồ sequence, class, ER, state sử dụng Mermaid v11.',
  },
  {
    id: 'ck:mintlify',
    title: 'Trang tài liệu với Mintlify',
    description: 'MDX components, theme, OpenAPI.',
  },
  {
    id: 'ck:mobile-development',
    title: 'React Native, Flutter, Swift, Kotlin',
    description: 'Hỗ trợ SwiftUI và Jetpack Compose.',
  },
  {
    id: 'ck:payment-integration',
    title: 'SePay, Polar, Stripe, Paddle, Creem.io',
    description: 'VietQR và các nhà cung cấp thanh toán quốc tế.',
  },
  {
    id: 'ck:plan',
    title: 'Tạo kế hoạch triển khai chi tiết',
    description:
      'Chế độ research, validation, và archival. Dùng subcommand archive, red-team, validate.',
    argsHint: 'archive red-team validate --auto --fast --hard --parallel --two --no-tasks',
  },
  {
    id: 'ck:plans-kanban',
    title: 'Bảng kế hoạch với theo dõi tiến độ',
    description: 'Trực quan hóa timeline và tiến độ.',
  },
  {
    id: 'ck:preview',
    title: 'Xem file hoặc tạo giải thích trực quan',
    description: 'Xem file theo đường dẫn hoặc tạo biểu đồ, slides, ASCII art.',
    argsHint: '--explain --slides --diagram --ascii',
  },
  {
    id: 'ck:problem-solving',
    title: 'Gỡ bế tắc khi giải quyết vấn đề phức tạp',
    description: 'Phá vỡ vòng lặp phức tạp, thử nghiệm giả định, đơn giản hóa bài toán.',
  },
  {
    id: 'ck:project-management',
    title: 'Theo dõi tiến độ và quản lý Claude Tasks',
    description: 'Tạo báo cáo, phối hợp tài liệu. Tasks: status, hydrate, sync, report.',
    argsHint: 'status hydrate sync report',
  },
  {
    id: 'ck:react-best-practices',
    title: 'Tối ưu hiệu suất React/Next.js',
    description: 'Từ các pattern của Vercel Engineering.',
  },
  {
    id: 'ck:remotion',
    title: 'Tạo video lập trình trong React',
    description: 'Xây dựng video components với React và render ra MP4.',
  },
  {
    id: 'ck:repomix',
    title: 'Đóng gói repositories thành file thân thiện với AI',
    description: 'Đầu ra định dạng XML, markdown, plain, hoặc JSON.',
    argsHint: '--style xml --style markdown --style plain --style json',
  },
  {
    id: 'ck:research',
    title: 'Nghiên cứu kỹ thuật và đánh giá công nghệ',
    description: 'Best practices, thiết kế giải pháp.',
    argsHint: '[topic]',
  },
  {
    id: 'ck:scout',
    title: 'Quét nhanh codebase',
    description: 'Các agent song song để khám phá file. Dùng flag ext để lọc theo loại file.',
    argsHint: '[search-target] [ext]',
  },
  {
    id: 'ck:sequential-thinking',
    title: 'Suy luận từng bước với khả năng tự điều chỉnh',
    description: 'Phân tích đa bước, kiểm chứng giả thuyết, lập kế hoạch thích ứng.',
  },
  {
    id: 'ck:shader',
    title: 'Viết GLSL fragment shaders',
    description: 'Đồ họa thủ tục và nghệ thuật sinh tạo. Hoạt động với Three.js.',
  },
  {
    id: 'ck:shopify',
    title: 'Ứng dụng Shopify và Liquid templates',
    description: 'Polaris UI, tùy chỉnh checkout.',
  },
  {
    id: 'ck:skill-creator',
    title: 'Tạo/cập nhật Claude skills',
    description: '3 sub-agent (analyzer, comparator, grader). Hạ tầng eval với benchmarks.',
  },
  {
    id: 'ck:tanstack',
    title: 'TanStack Start, Form, AI',
    description: 'Streaming/chat với TanStack AI.',
  },
  {
    id: 'ck:team',
    title: 'Điều phối Agent Teams',
    description: 'Cộng tác đa phiên song song. Template: research, implement, review, debug.',
    argsHint: '<template> <context> --devs N --researchers N --reviewers N --delegate',
  },
  {
    id: 'ck:test',
    title: 'Chạy test cục bộ và test UI',
    description: 'Chạy toàn bộ suite, module cụ thể, hoặc test UI trực quan trên website thực.',
    argsHint: '[context] ui [url]',
  },
  {
    id: 'ck:threejs',
    title: 'Xây dựng ứng dụng web 3D với Three.js',
    description: 'WebGL/WebGPU. 556 ví dụ, 60 API class.',
  },
  {
    id: 'ck:ui-styling',
    title: 'Tạo style UI với shadcn/ui',
    description: 'Radix UI + Tailwind CSS. Dark mode, hệ thống thiết kế.',
  },
  {
    id: 'ck:ui-ux-pro-max',
    title: '50+ styles, 161 bảng màu, 57 bộ font ghép đôi',
    description: '161 loại sản phẩm, 99 hướng dẫn UX, 25 loại chart, 10 stacks.',
  },
  {
    id: 'ck:use-mcp',
    title: 'Sử dụng MCP server tools',
    description: 'Khám phá và thực thi thông minh.',
  },
  {
    id: 'ck:watzup',
    title: 'Xem lại thay đổi gần đây và kết thúc phiên',
    description: 'Xem những gì đã thay đổi, review diff, và đóng phiên làm việc.',
  },
  {
    id: 'ck:web-design-guidelines',
    title: 'Đánh giá UI theo tiêu chuẩn Web Interface Guidelines',
    description: 'Kiểm tra code theo tiêu chuẩn design guidelines.',
  },
  {
    id: 'ck:web-frameworks',
    title: 'Monorepo Next.js, Turborepo',
    description: 'Hỗ trợ App Router, RSC, SSR, ISR.',
  },
  {
    id: 'ck:web-testing',
    title: 'Testing với Playwright, Vitest, k6',
    description: 'Test E2E/unit/integration/load/bảo mật/visual/a11y.',
  },
  {
    id: 'ck:worktree',
    title: 'Git worktree cô lập cho phát triển song song',
    description: 'Tạo feature branch trong thư mục riêng. Phù hợp cho monorepo.',
  },
] as const satisfies readonly EngineerKitStableCommand[];
